# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "ubt1404-contrail" do |node|
    node.vm.box = "ubt1404"
    node.vm.hostname = "ubt1404-contrail"
    node.vm.network "private_network", ip: "172.31.0.102"
    node.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", 2048]
      vbox.name		        = "ubt1404-contrail"
    end
  end

end


