# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.define "ubuntu-nfs" do |ubuntu|
    ubuntu.vm.box = "ubt1404"
    ubuntu.vm.hostname = "ubt1404-nfs"
    ubuntu.vm.network "private_network", ip: "172.31.0.101"
    ubuntu.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", 2048]
      vbox.name		        = "ubt1404-nfs"
    end
  end

end


